# ========================
# MAILING SERVICE CONFIGURATION
# ========================
spring.application.name=mailing-service
server.port=8085

# ========================
# DATABASE
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/tunindex-mailing
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========================
# Eureka Service Discovery
# ========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ========================
# EMAIL CONFIGURATION
# ========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=faresbenslama95@gmail.com
spring.mail.password=lntz cwsi uwbf fpwh
spring.mail.from=faresbenslama95@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ========================
# INTERNAL API KEY
# ========================
internal.api.key=market-tool-internal-secret-key-2026

# Mailing service URL for internal communication
mailing.service.url=http://mailing-service

# ========================
# API SERVICE URL
# ========================
api.service.url=http://api-service

# ========================
# LOGGING
# ========================
logging.level.com.tunindex.market_tool.mailing=DEBUG

# ========================
# SWAGGER
# ========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
