# ========================
# MAILING SERVICE CONFIGURATION
# ========================
spring.application.name=sms-service
server.port=8086

# ========================
# DATABASE
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/tunindex-sms
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========================
# Eureka Service Discovery
# ========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


# ========================
# INTERNAL API KEY
# ========================
internal.api.key=market-tool-internal-secret-key-2026

# Twilio Configuration
twilio.account_sid=6Ld3KEwrAAAAANrMHiNZJ7jj_b8ULoU9rRGBxCVG
twilio.auth_token=6Ld3KEwrAAAAAOgzWfBRBqyUSPt_i2n__rIoyUxa
twilio.trial_number=+14432643892

# ========================
# LOGGING
# ========================
logging.level.com.tunindex.market_tool.mailing=DEBUG

# ========================
# SWAGGER
# ========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
