spring.application.name=market-tool

# Server Port
server.port=8082

# JWT Settings
application.security.jwt.expiration=43200000
application.security.jwt.refresh-token.expiration=43200000

# RSA keys (paths relative to resources folder)
# JWT RSA keys
application.security.jwt.private-key=keys/private.pem
application.security.jwt.public-key=keys/public.pem


# Rest Template Configuration (if not already configured)
spring.http.client.read-timeout=10000


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tunindex
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# Logging
logging.level.com.example.prototype_project_marketing=INFO
logging.level.com.fares.stock.management.core.config.security.filters=INFO
logging.level.com.fares.stock.management.domain.controllers=INFO


# IP Security Config
application.security.ip-salt=d6f644b79a844c8a9b32f12e4a7c8d1e5f309a8714b247d5c12e8a7d6f4b29a

# Rate Limiter Configuration
security.rate-limit.enabled=true
security.rate-limit.second=10
security.rate-limit.minute=100
security.rate-limit.ip-ttl-minutes=5

# Exclusions (comma-separated)
security.rate-limit.exclude-paths=/api/public/**,/health,/actuator/**

# Response Configuration
security.rate-limit.error-message=Too many requests - please slow down


# Comma-separated list of trusted proxy IPs/CIDR ranges
application.security.trusted-proxies=

# CORS Monitoring Configuration
cors.monitoring.max-attempts-per-minute=100
cors.monitoring.max-attempts-per-hour=1000
cors.monitoring.suspicious-origins=



