spring.application.name=api-service
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tunindex
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Service Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30


application.security.jwt.private-key=keys/private.pem
application.security.jwt.public-key=keys/public.pem
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=172800000
application.security.ip-salt=d6f644b79a844c8a9b32f12e4a7c8d1e5f309a8714b247d5c12e8a7d6f4b29a
application.security.trusted-proxies=

# Logging
logging.level.com.tunindex.market_tool.api=DEBUG

# Make sure JPA repositories are scanned
spring.data.jpa.repositories.bootstrap-mode=default